import TabularTypeInterpreter.Syntax.ClassEnvironment
import TabularTypeInterpreter.Syntax.Kind
import TabularTypeInterpreter.Syntax.Term
import TabularTypeInterpreter.Syntax.Type
import TabularTypeInterpreter.Syntax.TypeEnvironment
