import TabularTypeInterpreter.Theorems.Generic
import TabularTypeInterpreter.Theorems.Kind
import TabularTypeInterpreter.Theorems.Program
import TabularTypeInterpreter.Theorems.Term
import TabularTypeInterpreter.Theorems.Type
