import TabularTypeInterpreter.Theorems.GenericEmulation
import TabularTypeInterpreter.Theorems.Kind
import TabularTypeInterpreter.Theorems.Program
import TabularTypeInterpreter.Theorems.Term
import TabularTypeInterpreter.Theorems.Type
