import TabularTypes.Semantics.Basic
import TabularTypes.Semantics.ClassEnvironment
import TabularTypes.Semantics.InstanceEnvironment
import TabularTypes.Semantics.Kind
import TabularTypes.Semantics.Program
import TabularTypes.Semantics.Term
import TabularTypes.Semantics.Type
import TabularTypes.Semantics.TypeEnvironment
