name: Build
on:
  push:
    branches: ["**"]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-lean-${{ hashFiles('lean-toolchain', 'lakefile.lean', 'lake-manifest.json') }}
        path: .lake
    - uses: Julian/setup-lean@v1
      with:
        default-toolchain-file: lean-toolchain
    - run: lake build
